### ISSUE TITLE
  // , How do I pick which API to use? 

### ISSUE THREAD

**Issue by v6** [Chip-Chap/shell-api#1]
// , I have tried, several times, to get some sort of authenticated access to the Chip Chap API. 

Do you have any specific use cases or examples of someone who has successfully accomplished this? 

Do you have any output code, or at least a screenshot I could look at?

**Comment by santoslluis** [comment]
hello @v6 I have to improve/finish this shell API, but you can try directly with HTTP requests, contact with support@chip-chap.com to get an account.
